
server:
  port: 7001
  servlet:
    context-path: /wxg

spring:
  application:
    name: wxg
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://182.92.179.169:5432/wxg_test
    username: postgres
    password: nzhk_lxy

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.nzhk.wxg

wxg:
  file:
    storage-dir: E:/data/wxg/uploads
    base-url: /wxg/file/access/
    sign-secret: ${WXG_FILE_SIGN_SECRET:wxg-file-secret}
    sign-expire-seconds: ${WXG_FILE_SIGN_EXPIRE:3600}
  wechat:
    appid: wxa46f1050fff7f28b
    secret: 275745dae4dda4a21b04497d7a3cdc9b
    subscribe-template-id: ZWGZk7oVGSlroh86kbxO4OZQ97pCeY-E2o2Sa15JqcU
